// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2x4TIaUVznmQjfHP8vm_F66Mnl2ve6CI',
    appId: '1:756876387267:web:08108e8d3547fd15725376',
    messagingSenderId: '756876387267',
    projectId: 'fir-test-26cb1',
    authDomain: 'fir-test-26cb1.firebaseapp.com',
    storageBucket: 'fir-test-26cb1.appspot.com',
    measurementId: 'G-YX68W8BM3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByfYYReljbeBX3yvOjP-fG7O5TfAVs7xs',
    appId: '1:756876387267:android:2120957a823adb2c725376',
    messagingSenderId: '756876387267',
    projectId: 'fir-test-26cb1',
    storageBucket: 'fir-test-26cb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAnF2DSGB0vTAPBtGr1Z5JyiMv7u2p5Bo',
    appId: '1:756876387267:ios:faaa0d132923cb65725376',
    messagingSenderId: '756876387267',
    projectId: 'fir-test-26cb1',
    storageBucket: 'fir-test-26cb1.appspot.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAnF2DSGB0vTAPBtGr1Z5JyiMv7u2p5Bo',
    appId: '1:756876387267:ios:c5bdc0156ce9ae84725376',
    messagingSenderId: '756876387267',
    projectId: 'fir-test-26cb1',
    storageBucket: 'fir-test-26cb1.appspot.com',
    iosBundleId: 'com.example.firebaseExample.RunnerTests',
  );
}
